### ISSUE TITLE
Slightly alter housing to help with the correct trackpad orientation

### ISSUE THREAD

**Issue by teije** [Rookwork/saucer-diy-voyager-trackpad#2]
In the section [Putting everything together](https://github.com/Rookwork/saucer-diy-voyager-trackpad?tab=readme-ov-file#putting-everything-together), you mention the relevance of the orientation of the trackpad and that it is tied to the 90 degrees value in the firmware. 

My sugguestion, to avoid assembly errors, is to add small bumps to the ring section of the housing. The cirque trackpad has holes for this exact purpose. 

![image](https://github.com/user-attachments/assets/7f56b19d-9668-4108-b1cd-a8eade33d123)

If you are ok with sharing the project file of the model, I would be happy to make this alteration and create a PR to add it to the project.

**Comment by Rookwork** [comment]
I actually originally had these pins in the design, but I found it difficult to get them to print precisely enough where they wouldn't interfere with the overall friction fit. Rather than spend too much time on trying to get them perfect, my thought is it's pretty quick to pop the trackpad in and out, so if you line it up slightly wrong at first, it's quick to fix.
